apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp
  namespace: familyman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp
  template:
    metadata:
      labels:
        app: dssp
    spec:
      containers:
      - name: dssp
        image: <initial-image>  # Specify a placeholder or the initial image
        ports:
        - containerPort: 80
